### ISSUE TITLE
Core Team & Advisors 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#8]
- SIZE: Could you make the core team & advisor visuals slightly smaller so we have 5 faces on 1 line on desktop? 

ADVISORS 
- Please add Trent as an advisor 
Name: Trent McConaghy
Bio http://trent.st (not https, doesn't work)
Twitter https://twitter.com/trentmc0  
no github link 
- Could you make sure have the legal council on a separate 2nd line? (griff request) So that means that you have only 4 advisors right now (place for a 5th) 
- for Patrick and Raphael you can just put 'Legal Council' and no links (so take away that one linkedin link)

**Comment by MaxSemenchuk** [comment]
1.1 SIZE: Could you make the core team & advisor visuals slightly smaller so we have 5 faces on 1 line on desktop?
Sorry – there's a limitation of Tilda, 4 max. I could create smth custom, but it will take a lot of time.

1.2 Please add Trent as an advisor
added

1.3 Could you make sure have the legal council on a separate 2nd line? (griff request) So that means that you have only 4 advisors right now (place for a 5th)
There're 6 already. Should i create a new group – Legal Council below the advisors or what? Or should I just add a line between council and no council? 

1.4 for Patrick and Raphael you can just put 'Legal Council' and no links (so take away that one linkedin link)
done

**Comment by krrisis** [comment]
Seeing point 1.1 I think we're good for now thx!
